---

- name: Install git
  win_chocolatey:
    name: git
    state: present
  tags: package


- name: Install notepadplusplus version latest
  win_chocolatey:
    name: notepadplusplus
    state: latest
  tags: package


- name: Install multiple packages
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
  - 7zip
  - putty
  tags: package

- name: Upgrade installed at last version
  win_chocolatey:
    name: all
    state: latest
  tags: update_package

- name: Install LibreOffice package
  win_chocolatey:
    name: libreoffice-fresh
    #become: yes
    #become_user: Administrator
    #become_method: runas
  tags: package

    #- name: uninstall multiple packages
    #win_chocolatey:
    #name: '{{ item }}'
    #state: absent
    #with_items:
    #- procexp
    #- putty
    #- windirstat

    #- name: Install curl using proxy
    # win_chocolatey:
    #name: curl
    #proxy_url: http://proxy-server:8080/
    #proxy_username: joe
    #proxy_password: p@ssw0rd

    #- name: Install curl with proxy credentials that contain quotes
    #win_chocolatey:
    #name: curl
    #proxy_url: http://proxy-server:8080/
    #proxy_username: user with \"escaped\" double quotes
    #proxy_password: pass with \"escaped\" double quotes

